---

name: Differential ShellCheck
on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04

    permissions:
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@d965e66ec0b3b2f821f75c8eff9b12442d9a7d1e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
